<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_apply.proto

namespace GPBMetadata\Plugin;

class HaiFriendApply
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab1020a1d706c7567696e2f6861695f667269656e645f6170706c792e70" .
            "726f746f1206706c7567696e22450a15486169467269656e644170706c79" .
            "5265717565737412160a0e736974655f667269656e645f69641801200128" .
            "0912140a0c6170706c795f726561736f6e18022001280922180a16486169" .
            "467269656e644170706c79526573706f6e7365325f0a1548616946726965" .
            "6e644170706c795365727669636512460a056170706c79121d2e706c7567" .
            "696e2e486169467269656e644170706c79526571756573741a1e2e706c75" .
            "67696e2e486169467269656e644170706c79526573706f6e7365423e0a17" .
            "636f6d2e616b6178696e2e70726f746f2e706c7567696e42134861694672" .
            "69656e644170706c7950726f746fca020d5a616c795c5365727669636573" .
            "620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

