<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_addMember.proto

namespace GPBMetadata\Plugin;

class HaiGroupAddMember
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4020a20706c7567696e2f6861695f67726f75705f6164644d656d6265" .
            "722e70726f746f1206706c7567696e22420a1848616947726f7570416464" .
            "4d656d6265725265717565737412100a0867726f75705f69641801200128" .
            "0912140a0c67726f75705f6d656d626572180220032809221b0a19486169" .
            "47726f75704164644d656d626572526573706f6e7365326c0a1848616947" .
            "726f75704164644d656d6265725365727669636512500a096164644d656d" .
            "62657212202e706c7567696e2e48616947726f75704164644d656d626572" .
            "526571756573741a212e706c7567696e2e48616947726f75704164644d65" .
            "6d626572526573706f6e736542410a17636f6d2e616b6178696e2e70726f" .
            "746f2e706c7567696e421648616947726f75704164644d656d6265725072" .
            "6f746fca020d5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

