<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_list.proto

namespace GPBMetadata\Plugin;

class HaiGroupList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0acd020a1b706c7567696e2f6861695f67726f75705f6c6973742e70726f" .
            "746f1206706c7567696e223d0a1348616947726f75704c69737452657175" .
            "65737412130a0b706167655f6e756d62657218012001280512110a097061" .
            "67655f73697a6518022001280522470a1448616947726f75704c69737452" .
            "6573706f6e7365122f0a0d67726f75705f70726f66696c6518012003280b" .
            "32182e636f72652e53696d706c6547726f757050726f66696c6532580a13" .
            "48616947726f75704c6973745365727669636512410a046c697374121b2e" .
            "706c7567696e2e48616947726f75704c697374526571756573741a1c2e70" .
            "6c7567696e2e48616947726f75704c697374526573706f6e7365423c0a17" .
            "636f6d2e616b6178696e2e70726f746f2e706c7567696e42114861694772" .
            "6f75704c69737450726f746fca020d5a616c795c53657276696365736206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

