<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_profile.proto

namespace GPBMetadata\Plugin;

class HaiGroupProfile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac3020a1e706c7567696e2f6861695f67726f75705f70726f66696c652e" .
            "70726f746f1206706c7567696e222a0a1648616947726f757050726f6669" .
            "6c655265717565737412100a0867726f75705f6964180120012809223e0a" .
            "1748616947726f757050726f66696c65526573706f6e736512230a077072" .
            "6f66696c6518012001280b32122e636f72652e47726f757050726f66696c" .
            "6532640a1648616947726f757050726f66696c6553657276696365124a0a" .
            "0770726f66696c65121e2e706c7567696e2e48616947726f757050726f66" .
            "696c65526571756573741a1f2e706c7567696e2e48616947726f75705072" .
            "6f66696c65526573706f6e7365423f0a17636f6d2e616b6178696e2e7072" .
            "6f746f2e706c7567696e421448616947726f757050726f66696c6550726f" .
            "746fca020d5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

