<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_delete.proto

namespace GPBMetadata\Plugin;

class HaiGroupDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a96020a1d706c7567696e2f6861695f67726f75705f64656c6574652e70" .
            "726f746f1206706c7567696e22290a1548616947726f757044656c657465" .
            "5265717565737412100a0867726f75705f696418012001280922180a1648" .
            "616947726f757044656c657465526573706f6e736532600a154861694772" .
            "6f757044656c6574655365727669636512470a0664656c657465121d2e70" .
            "6c7567696e2e48616947726f757044656c657465526571756573741a1e2e" .
            "706c7567696e2e48616947726f757044656c657465526573706f6e736542" .
            "3e0a17636f6d2e616b6178696e2e70726f746f2e706c7567696e42134861" .
            "6947726f757044656c65746550726f746fca020d5a616c795c5365727669" .
            "636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

