<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_removeMember.proto

namespace GPBMetadata\Plugin;

class HaiGroupRemoveMember
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0adc020a23706c7567696e2f6861695f67726f75705f72656d6f76654d65" .
            "6d6265722e70726f746f1206706c7567696e22450a1b48616947726f7570" .
            "52656d6f76654d656d6265725265717565737412100a0867726f75705f69" .
            "6418012001280912140a0c67726f75705f6d656d62657218032003280922" .
            "1e0a1c48616947726f757052656d6f76654d656d626572526573706f6e73" .
            "6532780a1b48616947726f757052656d6f76654d656d6265725365727669" .
            "636512590a0c72656d6f76654d656d62657212232e706c7567696e2e4861" .
            "6947726f757052656d6f76654d656d626572526571756573741a242e706c" .
            "7567696e2e48616947726f757052656d6f76654d656d626572526573706f" .
            "6e736542440a17636f6d2e616b6178696e2e70726f746f2e706c7567696e" .
            "421948616947726f757052656d6f76654d656d62657250726f746fca020d" .
            "5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

