<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_nonmembers.proto

namespace GPBMetadata\Plugin;

class HaiGroupNonmembers
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8e030a21706c7567696e2f6861695f67726f75705f6e6f6e6d656d6265" .
            "72732e70726f746f1206706c7567696e22550a1948616947726f75704e6f" .
            "6e6d656d626572735265717565737412100a0867726f75705f6964180120" .
            "01280912130a0b706167655f6e756d62657218022001280512110a097061" .
            "67655f73697a65180320012805224c0a1a48616947726f75704e6f6e6d65" .
            "6d62657273526573706f6e7365122e0a0c67726f75705f6d656d62657218" .
            "012003280b32182e636f72652e47726f75704d656d62657250726f66696c" .
            "6532700a1948616947726f75704e6f6e6d656d6265727353657276696365" .
            "12530a0a6e6f6e6d656d6265727312212e706c7567696e2e48616947726f" .
            "75704e6f6e6d656d62657273526571756573741a222e706c7567696e2e48" .
            "616947726f75704e6f6e6d656d62657273526573706f6e736542420a1763" .
            "6f6d2e616b6178696e2e70726f746f2e706c7567696e421748616947726f" .
            "75704e6f6e6d656d6265727350726f746fca020d5a616c795c5365727669" .
            "636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

