<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_updateProfile.proto

namespace GPBMetadata\Plugin;

class HaiGroupUpdateProfile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae1020a24706c7567696e2f6861695f67726f75705f7570646174655072" .
            "6f66696c652e70726f746f1206706c7567696e22430a1c48616947726f75" .
            "7055706461746550726f66696c655265717565737412230a0770726f6669" .
            "6c6518012001280b32122e636f72652e47726f757050726f66696c65221f" .
            "0a1d48616947726f757055706461746550726f66696c65526573706f6e73" .
            "65327c0a1c48616947726f757055706461746550726f66696c6553657276" .
            "696365125c0a0d75706461746550726f66696c6512242e706c7567696e2e" .
            "48616947726f757055706461746550726f66696c65526571756573741a25" .
            "2e706c7567696e2e48616947726f757055706461746550726f66696c6552" .
            "6573706f6e736542450a17636f6d2e616b6178696e2e70726f746f2e706c" .
            "7567696e421a48616947726f757055706461746550726f66696c6550726f" .
            "746fca020d5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

