<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_members.proto

namespace GPBMetadata\Plugin;

class HaiGroupMembers
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Group::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0af6020a1e706c7567696e2f6861695f67726f75705f6d656d626572732e" .
            "70726f746f1206706c7567696e22520a1648616947726f75704d656d6265" .
            "72735265717565737412100a0867726f75705f696418012001280912130a" .
            "0b706167655f6e756d62657218022001280512110a09706167655f73697a" .
            "6518032001280522490a1748616947726f75704d656d6265727352657370" .
            "6f6e7365122e0a0c67726f75705f6d656d62657218012003280b32182e63" .
            "6f72652e47726f75704d656d62657250726f66696c6532640a1648616947" .
            "726f75704d656d6265727353657276696365124a0a076d656d6265727312" .
            "1e2e706c7567696e2e48616947726f75704d656d62657273526571756573" .
            "741a1f2e706c7567696e2e48616947726f75704d656d6265727352657370" .
            "6f6e7365423f0a17636f6d2e616b6178696e2e70726f746f2e706c756769" .
            "6e421448616947726f75704d656d6265727350726f746fca020d5a616c79" .
            "5c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

