<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_delete.proto

namespace GPBMetadata\Plugin;

class HaiPluginDelete
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a98020a1e706c7567696e2f6861695f706c7567696e5f64656c6574652e" .
            "70726f746f120473697465222b0a16486169506c7567696e44656c657465" .
            "5265717565737412110a09706c7567696e5f696418012001280922190a17" .
            "486169506c7567696e44656c657465526573706f6e7365325f0a16486169" .
            "506c7567696e44656c6574655365727669636512450a0664656c65746512" .
            "1c2e736974652e486169506c7567696e44656c657465526571756573741a" .
            "1d2e736974652e486169506c7567696e44656c657465526573706f6e7365" .
            "423f0a17636f6d2e616b6178696e2e70726f746f2e706c7567696e421448" .
            "6169506c7567696e44656c65746550726f746fca020d5a616c795c536572" .
            "7669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

