<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_list.proto

namespace GPBMetadata\Plugin;

class HaiPluginList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac1020a1c706c7567696e2f6861695f706c7567696e5f6c6973742e7072" .
            "6f746f1206706c7567696e223e0a14486169506c7567696e4c6973745265" .
            "717565737412130a0b706167655f6e756d62657218012001280512110a09" .
            "706167655f73697a6518022001280522350a15486169506c7567696e4c69" .
            "7374526573706f6e7365121c0a06706c7567696e18012003280b320c2e63" .
            "6f72652e506c7567696e325b0a14486169506c7567696e4c697374536572" .
            "7669636512430a046c697374121c2e706c7567696e2e486169506c756769" .
            "6e4c697374526571756573741a1d2e706c7567696e2e486169506c756769" .
            "6e4c697374526573706f6e7365423d0a17636f6d2e616b6178696e2e7072" .
            "6f746f2e706c7567696e4212486169506c7567696e4c69737450726f746f" .
            "ca020d5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

