<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_add.proto

namespace GPBMetadata\Plugin;

class HaiPluginAdd
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a91020a1b706c7567696e2f6861695f706c7567696e5f6164642e70726f" .
            "746f1206706c7567696e22330a13486169506c7567696e41646452657175" .
            "657374121c0a06706c7567696e18012001280b320c2e636f72652e506c75" .
            "67696e22160a14486169506c7567696e416464526573706f6e736532570a" .
            "13486169506c7567696e4164645365727669636512400a03616464121b2e" .
            "706c7567696e2e486169506c7567696e416464526571756573741a1c2e70" .
            "6c7567696e2e486169506c7567696e416464526573706f6e7365423c0a17" .
            "636f6d2e616b6178696e2e70726f746f2e706c7567696e4211486169506c" .
            "7567696e41646450726f746fca020d5a616c795c53657276696365736206" .
            "70726f746f33"
        ));

        static::$is_initialized = true;
    }
}

