<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_profile.proto

namespace GPBMetadata\Plugin;

class HaiPluginProfile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0abe020a1f706c7567696e2f6861695f706c7567696e5f70726f66696c65" .
            "2e70726f746f120473697465222c0a17486169506c7567696e50726f6669" .
            "6c655265717565737412110a09706c7567696e5f69641801200128092238" .
            "0a18486169506c7567696e50726f66696c65526573706f6e7365121c0a06" .
            "706c7567696e18012001280b320c2e636f72652e506c7567696e32630a17" .
            "486169506c7567696e50726f66696c655365727669636512480a0770726f" .
            "66696c65121d2e736974652e486169506c7567696e50726f66696c655265" .
            "71756573741a1e2e736974652e486169506c7567696e50726f66696c6552" .
            "6573706f6e736542400a17636f6d2e616b6178696e2e70726f746f2e706c" .
            "7567696e4215486169506c7567696e50726f66696c6550726f746fca020d" .
            "5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

