<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_update.proto

namespace GPBMetadata\Plugin;

class HaiPluginUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Plugin::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa3020a1e706c7567696e2f6861695f706c7567696e5f7570646174652e" .
            "70726f746f12047369746522360a16486169506c7567696e557064617465" .
            "52657175657374121c0a06706c7567696e18012001280b320c2e636f7265" .
            "2e506c7567696e22190a17486169506c7567696e55706461746552657370" .
            "6f6e7365325f0a16486169506c7567696e55706461746553657276696365" .
            "12450a06757064617465121c2e736974652e486169506c7567696e557064" .
            "617465526571756573741a1d2e736974652e486169506c7567696e557064" .
            "617465526573706f6e7365423f0a17636f6d2e616b6178696e2e70726f74" .
            "6f2e706c7567696e4214486169506c7567696e55706461746550726f746f" .
            "ca020d5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

