<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_site_getConfig.proto

namespace GPBMetadata\Plugin;

class HaiSiteGetConfig
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Config::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac0020a1f706c7567696e2f6861695f736974655f676574436f6e666967" .
            "2e70726f746f1206706c7567696e22190a1748616953697465476574436f" .
            "6e6669675265717565737422450a1848616953697465476574436f6e6669" .
            "67526573706f6e736512290a0b736974655f636f6e66696718012001280b" .
            "32142e636f72652e536974654261636b436f6e66696732690a1748616953" .
            "697465476574436f6e66696753657276696365124e0a09676574436f6e66" .
            "6967121f2e706c7567696e2e48616953697465476574436f6e6669675265" .
            "71756573741a202e706c7567696e2e48616953697465476574436f6e6669" .
            "67526573706f6e736542400a17636f6d2e616b6178696e2e70726f746f2e" .
            "706c7567696e421548616953697465476574436f6e66696750726f746fca" .
            "020d5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

