<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_site_updateConfig.proto

namespace GPBMetadata\Plugin;

class HaiSiteUpdateConfig
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Config::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad8020a22706c7567696e2f6861695f736974655f757064617465436f6e" .
            "6669672e70726f746f1206706c7567696e22470a1a486169536974655570" .
            "64617465436f6e6669675265717565737412290a0b736974655f636f6e66" .
            "696718012001280b32142e636f72652e536974654261636b436f6e666967" .
            "221d0a1b48616953697465557064617465436f6e666967526573706f6e73" .
            "6532750a1a48616953697465557064617465436f6e666967536572766963" .
            "6512570a0c757064617465436f6e66696712222e706c7567696e2e486169" .
            "53697465557064617465436f6e666967526571756573741a232e706c7567" .
            "696e2e48616953697465557064617465436f6e666967526573706f6e7365" .
            "42430a17636f6d2e616b6178696e2e70726f746f2e706c7567696e421848" .
            "616953697465557064617465436f6e66696750726f746fca020d5a616c79" .
            "5c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

