<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_uic_create.proto

namespace GPBMetadata\Plugin;

class HaiUicCreate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8a020a1b706c7567696e2f6861695f7569635f6372656174652e70726f" .
            "746f1206706c7567696e22290a1348616955696343726561746552657175" .
            "65737412120a0a7569635f6e756d62657218012001280522160a14486169" .
            "556963437265617465526573706f6e7365325a0a13486169556963437265" .
            "6174655365727669636512430a06637265617465121b2e706c7567696e2e" .
            "486169556963437265617465526571756573741a1c2e706c7567696e2e48" .
            "6169556963437265617465526573706f6e7365423c0a17636f6d2e616b61" .
            "78696e2e70726f746f2e706c7567696e4211486169556963437265617465" .
            "50726f746fca020d5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

