<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_relationList.proto

namespace GPBMetadata\Plugin;

class HaiUserRelationList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a86030a22706c7567696e2f6861695f757365725f72656c6174696f6e4c" .
            "6973742e70726f746f1206706c7567696e22440a1a486169557365725265" .
            "6c6174696f6e4c6973745265717565737412130a0b706167655f6e756d62" .
            "657218012001280512110a09706167655f73697a65180220012805224e0a" .
            "1b4861695573657252656c6174696f6e4c697374526573706f6e7365122f" .
            "0a0c757365725f70726f66696c6518012003280b32192e636f72652e5573" .
            "657252656c6174696f6e50726f66696c6532750a1a486169557365725265" .
            "6c6174696f6e4c6973745365727669636512570a0c72656c6174696f6e4c" .
            "69737412222e706c7567696e2e4861695573657252656c6174696f6e4c69" .
            "7374526571756573741a232e706c7567696e2e4861695573657252656c61" .
            "74696f6e4c697374526573706f6e736542430a17636f6d2e616b6178696e" .
            "2e70726f746f2e706c7567696e42184861695573657252656c6174696f6e" .
            "4c69737450726f746fca020d5a616c795c5365727669636573620670726f" .
            "746f33"
        ));

        static::$is_initialized = true;
    }
}

