<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_update.proto

namespace GPBMetadata\Plugin;

class HaiUserUpdate
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa6020a1c706c7567696e2f6861695f757365725f7570646174652e7072" .
            "6f746f1206706c7567696e223f0a14486169557365725570646174655265" .
            "717565737412270a0c757365725f70726f66696c6518012001280b32112e" .
            "636f72652e5573657250726f66696c6522170a1548616955736572557064" .
            "617465526573706f6e7365325d0a14486169557365725570646174655365" .
            "727669636512450a06757064617465121c2e706c7567696e2e4861695573" .
            "6572557064617465526571756573741a1d2e706c7567696e2e4861695573" .
            "6572557064617465526573706f6e7365423d0a17636f6d2e616b6178696e" .
            "2e70726f746f2e706c7567696e4212486169557365725570646174655072" .
            "6f746fca020d5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

