<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_search.proto

namespace GPBMetadata\Plugin;

class HaiUserSearch
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0afd020a1c706c7567696e2f6861695f757365725f7365617263682e7072" .
            "6f746f1206706c7567696e22670a14486169557365725365617263685265" .
            "717565737412140a0c736974655f757365725f696418012001280912110a" .
            "09757365725f6e616d6518022001280912130a0b706167655f6e756d6265" .
            "7218032001280512110a09706167655f73697a6518042001280522460a15" .
            "48616955736572536561726368526573706f6e7365122d0a0c757365725f" .
            "70726f66696c6518012003280b32172e636f72652e53696d706c65557365" .
            "7250726f66696c65325d0a14486169557365725365617263685365727669" .
            "636512450a06736561726368121c2e706c7567696e2e4861695573657253" .
            "6561726368526571756573741a1d2e706c7567696e2e4861695573657253" .
            "6561726368526573706f6e7365423d0a17636f6d2e616b6178696e2e7072" .
            "6f746f2e706c7567696e42124861695573657253656172636850726f746f" .
            "ca020d5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

