<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_uic_info.proto

namespace GPBMetadata\Plugin;

class HaiUicInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Uic::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa0020a19706c7567696e2f6861695f7569635f696e666f2e70726f746f" .
            "1206706c7567696e222c0a11486169556963496e666f5265717565737412" .
            "0a0a026964180120012805120b0a0375696318022001280922350a124861" .
            "69556963496e666f526573706f6e7365121f0a087569635f696e666f1802" .
            "2001280b320d2e636f72652e556963496e666f32520a1148616955696349" .
            "6e666f53657276696365123d0a04696e666f12192e706c7567696e2e4861" .
            "69556963496e666f526571756573741a1a2e706c7567696e2e4861695569" .
            "63496e666f526573706f6e7365423a0a17636f6d2e616b6178696e2e7072" .
            "6f746f2e706c7567696e420f486169556963496e666f50726f746fca020d" .
            "5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

