<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_profile.proto

namespace GPBMetadata\Plugin;

class HaiUserProfile
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac4020a1d706c7567696e2f6861695f757365725f70726f66696c652e70" .
            "726f746f1206706c7567696e222d0a154861695573657250726f66696c65" .
            "5265717565737412140a0c736974655f757365725f696418012001280922" .
            "410a164861695573657250726f66696c65526573706f6e736512270a0c75" .
            "7365725f70726f66696c6518012001280b32112e636f72652e5573657250" .
            "726f66696c6532610a154861695573657250726f66696c65536572766963" .
            "6512480a0770726f66696c65121d2e706c7567696e2e4861695573657250" .
            "726f66696c65526571756573741a1e2e706c7567696e2e48616955736572" .
            "50726f66696c65526573706f6e7365423e0a17636f6d2e616b6178696e2e" .
            "70726f746f2e706c7567696e42134861695573657250726f66696c655072" .
            "6f746fca020d5a616c795c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

