<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_uic_list.proto

namespace GPBMetadata\Plugin;

class HaiUicList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\Uic::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ad0020a19706c7567696e2f6861695f7569635f6c6973742e70726f746f" .
            "1206706c7567696e225c0a114861695569634c6973745265717565737412" .
            "130a0b706167655f6e756d62657218012001280512110a09706167655f73" .
            "697a65180220012805121f0a0673746174757318032001280e320f2e636f" .
            "72652e55696353746174757322350a124861695569634c69737452657370" .
            "6f6e7365121f0a087569635f696e666f18012003280b320d2e636f72652e" .
            "556963496e666f32520a114861695569634c69737453657276696365123d" .
            "0a046c69737412192e706c7567696e2e4861695569634c69737452657175" .
            "6573741a1a2e706c7567696e2e4861695569634c697374526573706f6e73" .
            "65423a0a17636f6d2e616b6178696e2e70726f746f2e706c7567696e420f" .
            "4861695569634c69737450726f746fca020d5a616c795c53657276696365" .
            "73620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

