<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/config.proto

namespace Zaly\Services;

/**
 * Protobuf enum <code>Core\ConfigKey</code>
 */
class ConfigKey
{
    /**
     *站点地址
     *
     * Generated from protobuf enum <code>SITE_ADDRESS = 0;</code>
     */
    const SITE_ADDRESS = 0;
    /**
     *站点端口
     *
     * Generated from protobuf enum <code>SITE_PORT = 1;</code>
     */
    const SITE_PORT = 1;
    /**
     *站点名称
     *
     * Generated from protobuf enum <code>SITE_NAME = 2;</code>
     */
    const SITE_NAME = 2;
    /**
     *站点logo
     *
     * Generated from protobuf enum <code>SITE_LOGO = 3;</code>
     */
    const SITE_LOGO = 3;
    /**
     *站点版本
     *
     * Generated from protobuf enum <code>SITE_VERSION = 4;</code>
     */
    const SITE_VERSION = 4;
    /**
     *站点介绍
     *
     * Generated from protobuf enum <code>SITE_INTRODUCTION = 5;</code>
     */
    const SITE_INTRODUCTION = 5;
    /**
     *站点注册方式 RegisterWay
     *
     * Generated from protobuf enum <code>REGISTER_WAY = 6;</code>
     */
    const REGISTER_WAY = 6;
    /**
     *站点支持群最大成员数
     *
     * Generated from protobuf enum <code>GROUP_MEMBERS_COUNT = 7;</code>
     */
    const GROUP_MEMBERS_COUNT = 7;
    /**
     *站点图片支持最大尺寸
     *
     * Generated from protobuf enum <code>PIC_SIZE = 8;</code>
     */
    const PIC_SIZE = 8;
    /**
     *站点图片存放位置
     *
     * Generated from protobuf enum <code>PIC_PATH = 9;</code>
     */
    const PIC_PATH = 9;
    /**
     *站点状态，站点关闭(status=0)/站点开启(status=1)
     *
     * Generated from protobuf enum <code>SITE_STATUS = 10;</code>
     */
    const SITE_STATUS = 10;
    /**
     *站点关闭情况下，需要一个说明
     *
     * Generated from protobuf enum <code>SITE_STATUS_INFO = 11;</code>
     */
    const SITE_STATUS_INFO = 11;
    /**
     *站点超级管理员，唯一一个用户
     *
     * Generated from protobuf enum <code>SITE_ADMIN = 12;</code>
     */
    const SITE_ADMIN = 12;
    /**
     *站点http服务地址
     *
     * Generated from protobuf enum <code>SITE_HTTP_ADDRESS = 13;</code>
     */
    const SITE_HTTP_ADDRESS = 13;
    /**
     *站点http服务地址ip
     *
     * Generated from protobuf enum <code>SITE_HTTP_PORT = 14;</code>
     */
    const SITE_HTTP_PORT = 14;
    /**
     *二人消息绝密功能是否开启
     *
     * Generated from protobuf enum <code>U2_ENCRYPTION_STATUS = 15;</code>
     */
    const U2_ENCRYPTION_STATUS = 15;
    /**
     *数据库路径
     *
     * Generated from protobuf enum <code>DB_PATH = 16;</code>
     */
    const DB_PATH = 16;
    /**
     *PushClientStatus
     *
     * Generated from protobuf enum <code>PUSH_CLIENT_STATUS = 17;</code>
     */
    const PUSH_CLIENT_STATUS = 17;
    /**
     *系统的日志级别 DEBUG/INFO/ERROR
     *
     * Generated from protobuf enum <code>LOG_LEVEL = 18;</code>
     */
    const LOG_LEVEL = 18;
    /**
     *站点管理员，多个用户，用“,”隔开
     *
     * Generated from protobuf enum <code>SITE_MANAGER = 19;</code>
     */
    const SITE_MANAGER = 19;
}

