<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * 错误信息
 *code="success" 请求成功
 *code="error" 请求失败，客户端不做任何处理
 *code="error.alter" 请求失败，客户端展示错误info
 *code="error.session" api请求||im请求校验session失败
 *code="error.login.need_register" 用户登陆返回此值需要告诉用户注册
 *code="error.login.needRegister" 用户登陆返回此值需要告诉用户注册
 *code="error.phone.same" 用户绑定身份，表示二者已经存在绑定
 *
 * Generated from protobuf message <code>core.ErrorInfo</code>
 */
class ErrorInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string code = 1;</code>
     */
    private $code = '';
    /**
     * Generated from protobuf field <code>string info = 2;</code>
     */
    private $info = '';

    public function __construct() {
        \GPBMetadata\Core\Core::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @return string
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * Generated from protobuf field <code>string code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string info = 2;</code>
     * @return string
     */
    public function getInfo()
    {
        return $this->info;
    }

    /**
     * Generated from protobuf field <code>string info = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->info = $var;

        return $this;
    }

}

