<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace Zaly\Services;

/**
 * Protobuf enum <code>Core\GroupMemberRole</code>
 */
class GroupMemberRole
{
    /**
     *非群成员
     *
     * Generated from protobuf enum <code>NONMEMBER = 0;</code>
     */
    const NONMEMBER = 0;
    /**
     *群成员
     *
     * Generated from protobuf enum <code>MEMBER = 1;</code>
     */
    const MEMBER = 1;
    /**
     *群所有者
     *
     * Generated from protobuf enum <code>OWNER = 2;</code>
     */
    const OWNER = 2;
    /**
     *群管理员
     *
     * Generated from protobuf enum <code>ADMIN = 3;</code>
     */
    const ADMIN = 3;
}

