<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace Zaly\Services;

/**
 * Protobuf enum <code>Core\GroupStatus</code>
 */
class GroupStatus
{
    /**
     *已经解散的群组
     *
     * Generated from protobuf enum <code>GROUP_DELETE = 0;</code>
     */
    const GROUP_DELETE = 0;
    /**
     *正常的群组
     *
     * Generated from protobuf enum <code>GROUP_NORMAL = 1;</code>
     */
    const GROUP_NORMAL = 1;
}

