<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *消息通知：群组消息文本通知消息
 *
 * Generated from protobuf message <code>core.GroupMsgNotice</code>
 */
class GroupMsgNotice extends \Google\Protobuf\Internal\Message
{
    /**
     *通知发送者
     *
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     */
    private $site_user_id = '';
    /**
     *群组ID
     *
     * Generated from protobuf field <code>string site_group_id = 2;</code>
     */
    private $site_group_id = '';
    /**
     *通知消息
     *
     * Generated from protobuf field <code>bytes text = 3;</code>
     */
    private $text = '';
    /**
     *消息时间，单位ms
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     */
    private $time = 0;

    public function __construct() {
        \GPBMetadata\Core\Core::initOnce();
        parent::__construct();
    }

    /**
     *通知发送者
     *
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     *通知发送者
     *
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *群组ID
     *
     * Generated from protobuf field <code>string site_group_id = 2;</code>
     * @return string
     */
    public function getSiteGroupId()
    {
        return $this->site_group_id;
    }

    /**
     *群组ID
     *
     * Generated from protobuf field <code>string site_group_id = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_group_id = $var;

        return $this;
    }

    /**
     *通知消息
     *
     * Generated from protobuf field <code>bytes text = 3;</code>
     * @return string
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     *通知消息
     *
     * Generated from protobuf field <code>bytes text = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setText($var)
    {
        GPBUtil::checkString($var, False);
        $this->text = $var;

        return $this;
    }

    /**
     *消息时间，单位ms
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     * @return int|string
     */
    public function getTime()
    {
        return $this->time;
    }

    /**
     *消息时间，单位ms
     *
     * Generated from protobuf field <code>int64 time = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->time = $var;

        return $this;
    }

}

