<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>core.GroupMemberProfile</code>
 */
class GroupMemberProfile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.core.GroupMemberRole role = 1;</code>
     */
    private $role = 0;
    /**
     * Generated from protobuf field <code>.core.UserProfile profile = 2;</code>
     */
    private $profile = null;

    public function __construct() {
        \GPBMetadata\Core\Group::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.core.GroupMemberRole role = 1;</code>
     * @return int
     */
    public function getRole()
    {
        return $this->role;
    }

    /**
     * Generated from protobuf field <code>.core.GroupMemberRole role = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setRole($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Services\GroupMemberRole::class);
        $this->role = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.core.UserProfile profile = 2;</code>
     * @return \Zaly\Services\UserProfile
     */
    public function getProfile()
    {
        return $this->profile;
    }

    /**
     * Generated from protobuf field <code>.core.UserProfile profile = 2;</code>
     * @param \Zaly\Services\UserProfile $var
     * @return $this
     */
    public function setProfile($var)
    {
        GPBUtil::checkMessage($var, \Zaly\Services\UserProfile::class);
        $this->profile = $var;

        return $this;
    }

}

