<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_friend_apply.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiFriendApplyResponse</code>
 */
class HaiFriendApplyResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Plugin\HaiFriendApply::initOnce();
        parent::__construct();
    }

}

