<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_members.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiGroupMembersResponse</code>
 */
class HaiGroupMembersResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *群组成员信息
     *
     * Generated from protobuf field <code>repeated .core.GroupMemberProfile group_member = 1;</code>
     */
    private $group_member;

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupMembers::initOnce();
        parent::__construct();
    }

    /**
     *群组成员信息
     *
     * Generated from protobuf field <code>repeated .core.GroupMemberProfile group_member = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroupMember()
    {
        return $this->group_member;
    }

    /**
     *群组成员信息
     *
     * Generated from protobuf field <code>repeated .core.GroupMemberProfile group_member = 1;</code>
     * @param \Zaly\Services\GroupMemberProfile[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroupMember($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Services\GroupMemberProfile::class);
        $this->group_member = $arr;

        return $this;
    }

}

