<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_addMember.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiGroupAddMemberResponse</code>
 */
class HaiGroupAddMemberResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupAddMember::initOnce();
        parent::__construct();
    }

}

