<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_removeMember.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiGroupRemoveMemberRequest</code>
 */
class HaiGroupRemoveMemberRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *群组ID
     *
     * Generated from protobuf field <code>string group_id = 1;</code>
     */
    private $group_id = '';
    /**
     *需要删除的群组成员
     *
     * Generated from protobuf field <code>repeated string group_member = 3;</code>
     */
    private $group_member;

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupRemoveMember::initOnce();
        parent::__construct();
    }

    /**
     *群组ID
     *
     * Generated from protobuf field <code>string group_id = 1;</code>
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     *群组ID
     *
     * Generated from protobuf field <code>string group_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

    /**
     *需要删除的群组成员
     *
     * Generated from protobuf field <code>repeated string group_member = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroupMember()
    {
        return $this->group_member;
    }

    /**
     *需要删除的群组成员
     *
     * Generated from protobuf field <code>repeated string group_member = 3;</code>
     * @param string[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroupMember($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->group_member = $arr;

        return $this;
    }

}

