<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_group_delete.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiGroupDeleteRequest</code>
 */
class HaiGroupDeleteRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *删除的群组ID
     *
     * Generated from protobuf field <code>string group_id = 1;</code>
     */
    private $group_id = '';

    public function __construct() {
        \GPBMetadata\Plugin\HaiGroupDelete::initOnce();
        parent::__construct();
    }

    /**
     *删除的群组ID
     *
     * Generated from protobuf field <code>string group_id = 1;</code>
     * @return string
     */
    public function getGroupId()
    {
        return $this->group_id;
    }

    /**
     *删除的群组ID
     *
     * Generated from protobuf field <code>string group_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->group_id = $var;

        return $this;
    }

}

