<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_profile.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>site.HaiPluginProfileRequest</code>
 */
class HaiPluginProfileRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *插件id
     *
     * Generated from protobuf field <code>string plugin_id = 1;</code>
     */
    private $plugin_id = '';

    public function __construct() {
        \GPBMetadata\Plugin\HaiPluginProfile::initOnce();
        parent::__construct();
    }

    /**
     *插件id
     *
     * Generated from protobuf field <code>string plugin_id = 1;</code>
     * @return string
     */
    public function getPluginId()
    {
        return $this->plugin_id;
    }

    /**
     *插件id
     *
     * Generated from protobuf field <code>string plugin_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPluginId($var)
    {
        GPBUtil::checkString($var, True);
        $this->plugin_id = $var;

        return $this;
    }

}

