<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_plugin_add.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiPluginAddResponse</code>
 */
class HaiPluginAddResponse extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Plugin\HaiPluginAdd::initOnce();
        parent::__construct();
    }

}

