<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_site_getConfig.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiSiteGetConfigRequest</code>
 */
class HaiSiteGetConfigRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Plugin\HaiSiteGetConfig::initOnce();
        parent::__construct();
    }

}

