<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_user_sealUp.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiUserSealUpRequest</code>
 */
class HaiUserSealUpRequest extends \Google\Protobuf\Internal\Message
{
    /**
     *需要删除的用户ID
     *
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     */
    private $site_user_id = '';
    /**
     *用户状态
     *
     * Generated from protobuf field <code>.core.UserStatus status = 2;</code>
     */
    private $status = 0;

    public function __construct() {
        \GPBMetadata\Plugin\HaiUserSealUp::initOnce();
        parent::__construct();
    }

    /**
     *需要删除的用户ID
     *
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     * @return string
     */
    public function getSiteUserId()
    {
        return $this->site_user_id;
    }

    /**
     *需要删除的用户ID
     *
     * Generated from protobuf field <code>string site_user_id = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSiteUserId($var)
    {
        GPBUtil::checkString($var, True);
        $this->site_user_id = $var;

        return $this;
    }

    /**
     *用户状态
     *
     * Generated from protobuf field <code>.core.UserStatus status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     *用户状态
     *
     * Generated from protobuf field <code>.core.UserStatus status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Zaly\Services\UserStatus::class);
        $this->status = $var;

        return $this;
    }

}

