<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: plugin/hai_uic_list.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>plugin.HaiUicListResponse</code>
 */
class HaiUicListResponse extends \Google\Protobuf\Internal\Message
{
    /**
     *查询的UIC结果
     *
     * Generated from protobuf field <code>repeated .core.UicInfo uic_info = 1;</code>
     */
    private $uic_info;

    public function __construct() {
        \GPBMetadata\Plugin\HaiUicList::initOnce();
        parent::__construct();
    }

    /**
     *查询的UIC结果
     *
     * Generated from protobuf field <code>repeated .core.UicInfo uic_info = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUicInfo()
    {
        return $this->uic_info;
    }

    /**
     *查询的UIC结果
     *
     * Generated from protobuf field <code>repeated .core.UicInfo uic_info = 1;</code>
     * @param \Zaly\Services\UicInfo[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUicInfo($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Zaly\Services\UicInfo::class);
        $this->uic_info = $arr;

        return $this;
    }

}

