<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core.proto

namespace Zaly\Services;

/**
 * Protobuf enum <code>Core\HeaderKey</code>
 */
class HeaderKey
{
    /**
     *0-500 分配给CLIENT_SOCKET
     *
     * Generated from protobuf enum <code>CLIENT_SOCKET_VERSION = 0;</code>
     */
    const CLIENT_SOCKET_VERSION = 0;
    /**
     * Generated from protobuf enum <code>CLIENT_SOCKET_SITE_SESSION_ID = 1;</code>
     */
    const CLIENT_SOCKET_SITE_SESSION_ID = 1;
    /**
     * Generated from protobuf enum <code>CLIENT_SOCKET_PLATFORM_SESSION_ID = 2;</code>
     */
    const CLIENT_SOCKET_PLATFORM_SESSION_ID = 2;
    /**
     * Generated from protobuf enum <code>CLIENT_SOCKET_DEVICE_ID = 3;</code>
     */
    const CLIENT_SOCKET_DEVICE_ID = 3;
    /**
     * 客户端正在使用的语言, cn/en
     *
     * Generated from protobuf enum <code>CLIENT_SOCKET_LANGUAGE = 4;</code>
     */
    const CLIENT_SOCKET_LANGUAGE = 4;
    /**
     * 客户端类型，见client.proto中的ClientType
     *
     * Generated from protobuf enum <code>CLIENT_SOCKET_TYPE = 5;</code>
     */
    const CLIENT_SOCKET_TYPE = 5;
    /**
     *501-1000 分配给CLIENT_REQUEST
     *
     * Generated from protobuf enum <code>CLIENT_REQUEST_REFERER = 501;</code>
     */
    const CLIENT_REQUEST_REFERER = 501;
    /**
     *客户端访问的服务host
     *
     * Generated from protobuf enum <code>CLIENT_REQUEST_SERVER_HOST = 502;</code>
     */
    const CLIENT_REQUEST_SERVER_HOST = 502;
    /**
     *客户端访问的服务port
     *
     * Generated from protobuf enum <code>CLIENT_REQUEST_SERVER_PORT = 503;</code>
     */
    const CLIENT_REQUEST_SERVER_PORT = 503;
    /**
     *1001-2000 分配给SITE_SERVER
     *
     * Generated from protobuf enum <code>SITE_SERVER_VERSION = 1001;</code>
     */
    const SITE_SERVER_VERSION = 1001;
    /**
     *服务端host
     *
     * Generated from protobuf enum <code>SITE_SERVER_HOST = 1002;</code>
     */
    const SITE_SERVER_HOST = 1002;
    /**
     *服务端port
     *
     * Generated from protobuf enum <code>SITE_SERVER_PORT = 1003;</code>
     */
    const SITE_SERVER_PORT = 1003;
    /**
     *3001-4000 分配给PLUGIN
     *
     * Generated from protobuf enum <code>PLUGIN_CLIENT_REFERER = 3001;</code>
     */
    const PLUGIN_CLIENT_REFERER = 3001;
}

