<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *这个不是废弃了么？
 *
 * Generated from protobuf message <code>core.MsgFinish</code>
 */
class MsgFinish extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\Core\Core::initOnce();
        parent::__construct();
    }

}

