<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/core.proto

namespace Zaly\Services;

/**
 *以下内容为共用消息内容
 *消息类型
 *
 * Protobuf enum <code>Core\MsgType</code>
 */
class MsgType
{
    /**
     *系统通知
     *
     * Generated from protobuf enum <code>NOTICE = 0;</code>
     */
    const NOTICE = 0;
    /**
     * Generated from protobuf enum <code>MSG_STATUS = 1;</code>
     */
    const MSG_STATUS = 1;
    /**
     *这个不是废弃了么？
     *
     * Generated from protobuf enum <code>MSG_FINISH = 2;</code>
     */
    const MSG_FINISH = 2;
    /**
     * Generated from protobuf enum <code>TEXT = 3;</code>
     */
    const TEXT = 3;
    /**
     * Generated from protobuf enum <code>SECRET_TEXT = 4;</code>
     */
    const SECRET_TEXT = 4;
    /**
     * Generated from protobuf enum <code>GROUP_TEXT = 5;</code>
     */
    const GROUP_TEXT = 5;
    /**
     * Generated from protobuf enum <code>GROUP_SECRET_TEXT = 6;</code>
     */
    const GROUP_SECRET_TEXT = 6;
    /**
     * Generated from protobuf enum <code>IMAGE = 7;</code>
     */
    const IMAGE = 7;
    /**
     * Generated from protobuf enum <code>SECRET_IMAGE = 8;</code>
     */
    const SECRET_IMAGE = 8;
    /**
     * Generated from protobuf enum <code>GROUP_IMAGE = 9;</code>
     */
    const GROUP_IMAGE = 9;
    /**
     * Generated from protobuf enum <code>GROUP_SECRET_IMAGE = 10;</code>
     */
    const GROUP_SECRET_IMAGE = 10;
    /**
     * Generated from protobuf enum <code>VOICE = 11;</code>
     */
    const VOICE = 11;
    /**
     * Generated from protobuf enum <code>SECRET_VOICE = 12;</code>
     */
    const SECRET_VOICE = 12;
    /**
     * Generated from protobuf enum <code>GROUP_VOICE = 13;</code>
     */
    const GROUP_VOICE = 13;
    /**
     * Generated from protobuf enum <code>GROUP_SECRET_VOICE = 14;</code>
     */
    const GROUP_SECRET_VOICE = 14;
    /**
     * Generated from protobuf enum <code>MAP = 15;</code>
     */
    const MAP = 15;
    /**
     * Generated from protobuf enum <code>SECRET_MAP = 16;</code>
     */
    const SECRET_MAP = 16;
    /**
     * Generated from protobuf enum <code>GROUP_MAP = 17;</code>
     */
    const GROUP_MAP = 17;
    /**
     * Generated from protobuf enum <code>GROUP_SECRET_MAP = 18;</code>
     */
    const GROUP_SECRET_MAP = 18;
    /**
     *二人消息中的通知消息
     *
     * Generated from protobuf enum <code>U2_NOTICE = 19;</code>
     */
    const U2_NOTICE = 19;
    /**
     *群消息中的通知消息
     *
     * Generated from protobuf enum <code>GROUP_NOTICE = 20;</code>
     */
    const GROUP_NOTICE = 20;
}

