<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/plugin.proto

namespace Zaly\Services;

/**
 * Protobuf enum <code>Core\PermissionStatus</code>
 */
class PermissionStatus
{
    /**
     *禁用状态
     *
     * Generated from protobuf enum <code>DISABLED = 0;</code>
     */
    const DISABLED = 0;
    /**
     *可用状态
     *
     * Generated from protobuf enum <code>AVAILABLE = 1;</code>
     */
    const AVAILABLE = 1;
}

