<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/plugin.proto

namespace Zaly\Services;

/**
 * Protobuf enum <code>Core\PluginPosition</code>
 */
class PluginPosition
{
    /**
     *首页位置
     *
     * Generated from protobuf enum <code>HOME_PAGE = 0;</code>
     */
    const HOME_PAGE = 0;
    /**
     *消息帧位置
     *
     * Generated from protobuf enum <code>MSG_PAGE = 1;</code>
     */
    const MSG_PAGE = 1;
}

