<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/plugin.proto

namespace Zaly\Services;

/**
 *header 里面
 *
 * Protobuf enum <code>Core\PluginHeaderKey</code>
 */
class PluginHeaderKey
{
    /**
     * Generated from protobuf enum <code>CLIENT_VERSION = 0;</code>
     */
    const CLIENT_VERSION = 0;
    /**
     *当前客户端用户ID
     *
     * Generated from protobuf enum <code>CLIENT_SITE_USER_ID = 1;</code>
     */
    const CLIENT_SITE_USER_ID = 1;
    /**
     *当前用户的sessionID
     *
     * Generated from protobuf enum <code>CLIENT_SITE_SESSION_ID = 2;</code>
     */
    const CLIENT_SITE_SESSION_ID = 2;
    /**
     *使用zaly:goto
     *
     * Generated from protobuf enum <code>PLUGIN_REFERER = 3;</code>
     */
    const PLUGIN_REFERER = 3;
    /**
     *单位ms
     *
     * Generated from protobuf enum <code>PLUGIN_TIMESTAMP = 4;</code>
     */
    const PLUGIN_TIMESTAMP = 4;
    /**
     *扩展的ID
     *
     * Generated from protobuf enum <code>PLUGIN_ID = 5;</code>
     */
    const PLUGIN_ID = 5;
}

