<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/plugin.proto

namespace Zaly\Services;

/**
 * Protobuf enum <code>Core\PluginDisplayMode</code>
 */
class PluginDisplayMode
{
    /**
     *默认，新页面
     *
     * Generated from protobuf enum <code>NEW_PAGE = 0;</code>
     */
    const NEW_PAGE = 0;
    /**
     *浮屏
     *
     * Generated from protobuf enum <code>FLOATING_SCREEN = 1;</code>
     */
    const FLOATING_SCREEN = 1;
    /**
     *分屏
     *
     * Generated from protobuf enum <code>SPLIT_SCREEN = 2;</code>
     */
    const SPLIT_SCREEN = 2;
}

