<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/plugin.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * site 与plugin之间交互传输的package包
 *
 * Generated from protobuf message <code>core.ProxyPluginPackage</code>
 */
class ProxyPluginPackage extends \Google\Protobuf\Internal\Message
{
    /**
     *header
     *
     * Generated from protobuf field <code>map<int32, string> plugin_header = 1;</code>
     */
    private $plugin_header;
    /**
     *data在赋值之前先base64
     *site -> plugin 是开发者自定义的格式
     *plugin -> site 为具体请求的proto格式
     *
     * Generated from protobuf field <code>string data = 2;</code>
     */
    private $data = '';
    /**
     *error信息
     *
     * Generated from protobuf field <code>.core.ErrorInfo error_info = 3;</code>
     */
    private $error_info = null;

    public function __construct() {
        \GPBMetadata\Core\Plugin::initOnce();
        parent::__construct();
    }

    /**
     *header
     *
     * Generated from protobuf field <code>map<int32, string> plugin_header = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getPluginHeader()
    {
        return $this->plugin_header;
    }

    /**
     *header
     *
     * Generated from protobuf field <code>map<int32, string> plugin_header = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setPluginHeader($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::STRING);
        $this->plugin_header = $arr;

        return $this;
    }

    /**
     *data在赋值之前先base64
     *site -> plugin 是开发者自定义的格式
     *plugin -> site 为具体请求的proto格式
     *
     * Generated from protobuf field <code>string data = 2;</code>
     * @return string
     */
    public function getData()
    {
        return $this->data;
    }

    /**
     *data在赋值之前先base64
     *site -> plugin 是开发者自定义的格式
     *plugin -> site 为具体请求的proto格式
     *
     * Generated from protobuf field <code>string data = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setData($var)
    {
        GPBUtil::checkString($var, True);
        $this->data = $var;

        return $this;
    }

    /**
     *error信息
     *
     * Generated from protobuf field <code>.core.ErrorInfo error_info = 3;</code>
     * @return \Zaly\Services\ErrorInfo
     */
    public function getErrorInfo()
    {
        return $this->error_info;
    }

    /**
     *error信息
     *
     * Generated from protobuf field <code>.core.ErrorInfo error_info = 3;</code>
     * @param \Zaly\Services\ErrorInfo $var
     * @return $this
     */
    public function setErrorInfo($var)
    {
        GPBUtil::checkMessage($var, \Zaly\Services\ErrorInfo::class);
        $this->error_info = $var;

        return $this;
    }

}

