<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/config.proto

namespace Zaly\Services;

/**
 *站点的注册方式
 *
 * Protobuf enum <code>Core\RegisterWay</code>
 */
class RegisterWay
{
    /**
     *匿名方式
     *
     * Generated from protobuf enum <code>ANONYMOUS = 0;</code>
     */
    const ANONYMOUS = 0;
    /**
     *实名方式
     *
     * Generated from protobuf enum <code>REALNAME = 1;</code>
     */
    const REALNAME = 1;
    /**
     *用户邀请码方式
     *
     * Generated from protobuf enum <code>USERUIC = 2;</code>
     */
    const USERUIC = 2;
}

