<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/config.proto

namespace Zaly\Services;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *站点后台管理配置
 *
 * Generated from protobuf message <code>core.SiteBackConfig</code>
 */
class SiteBackConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<int32, string> site_config = 1;</code>
     */
    private $site_config;

    public function __construct() {
        \GPBMetadata\Core\Config::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>map<int32, string> site_config = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getSiteConfig()
    {
        return $this->site_config;
    }

    /**
     * Generated from protobuf field <code>map<int32, string> site_config = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setSiteConfig($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::INT32, \Google\Protobuf\Internal\GPBType::STRING);
        $this->site_config = $arr;

        return $this;
    }

}

