<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/config.proto

namespace Zaly\Services;

/**
 * Protobuf enum <code>Core\U2EncryptionStatus</code>
 */
class U2EncryptionStatus
{
    /**
     *二人加密关闭
     *
     * Generated from protobuf enum <code>U2_CLOSE = 0;</code>
     */
    const U2_CLOSE = 0;
    /**
     *二人加密开启
     *
     * Generated from protobuf enum <code>U2_OPEN = 1;</code>
     */
    const U2_OPEN = 1;
}

