<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/uic.proto

namespace Zaly\Services;

/**
 * Protobuf enum <code>Core\UicStatus</code>
 */
class UicStatus
{
    /**
     *未使用的的
     *
     * Generated from protobuf enum <code>UNUSED = 0;</code>
     */
    const UNUSED = 0;
    /**
     *已经使用的
     *
     * Generated from protobuf enum <code>USED = 1;</code>
     */
    const USED = 1;
    /**
     *失效的
     *
     * Generated from protobuf enum <code>INVALIDATION = 2;</code>
     */
    const INVALIDATION = 2;
}

