<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/user.proto

namespace Zaly\Services;

/**
 * Protobuf enum <code>Core\UserStatus</code>
 */
class UserStatus
{
    /**
     *正常用户
     *
     * Generated from protobuf enum <code>NORMAL = 0;</code>
     */
    const NORMAL = 0;
    /**
     *禁封用户
     *
     * Generated from protobuf enum <code>SEALUP = 1;</code>
     */
    const SEALUP = 1;
}

