<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/user.proto

namespace Zaly\Services;

/**
 * 针对当前用户A来说，用户B和A之间的关系
 *
 * Protobuf enum <code>Core\UserRelation</code>
 */
class UserRelation
{
    /**
     *用户无关系
     *
     * Generated from protobuf enum <code>RELATION_NONE = 0;</code>
     */
    const RELATION_NONE = 0;
    /**
     *用户之间为好友关系，AB互相为好友
     *
     * Generated from protobuf enum <code>RELATION_FRIEND = 1;</code>
     */
    const RELATION_FRIEND = 1;
    /**
     *A 关注 B（A添加B为好友，待B同意）
     *
     * Generated from protobuf enum <code>RELATION_CARE = 2;</code>
     */
    const RELATION_CARE = 2;
    /**
     *B 关注 A（B添加A为好友，待A同意）
     *
     * Generated from protobuf enum <code>RELATION_FANS = 3;</code>
     */
    const RELATION_FANS = 3;
}

