<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/group.proto

namespace GPBMetadata\Core;

class Group
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Core\User::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ac9030a10636f72652f67726f75702e70726f746f1204636f7265224c0a" .
            "0c47726f757050726f66696c65120a0a026964180120012809120c0a046e" .
            "616d65180220012809120c0a0469636f6e18042001280912140a0c67726f" .
            "75705f6e6f74696365180520012809224e0a1253696d706c6547726f7570" .
            "50726f66696c6512100a0867726f75705f696418012001280912120a0a67" .
            "726f75705f6e616d6518022001280912120a0a67726f75705f69636f6e18" .
            "0320012809225d0a1247726f75704d656d62657250726f66696c6512230a" .
            "04726f6c6518012001280e32152e636f72652e47726f75704d656d626572" .
            "526f6c6512220a0770726f66696c6518022001280b32112e636f72652e55" .
            "73657250726f66696c652a420a0f47726f75704d656d626572526f6c6512" .
            "0d0a094e4f4e4d454d4245521000120a0a064d454d424552100112090a05" .
            "4f574e4552100212090a0541444d494e10032a310a0b47726f7570537461" .
            "74757312100a0c47524f55505f44454c455445100012100a0c47524f5550" .
            "5f4e4f524d414c100142330a15636f6d2e616b6178696e2e70726f746f2e" .
            "636f7265420a47726f757050726f746fca020d5a616c795c536572766963" .
            "6573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

