<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: core/uic.proto

namespace GPBMetadata\Core;

class Uic
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a9c020a0e636f72652f7569632e70726f746f1204636f72652293010a07" .
            "556963496e666f120a0a026964180120012805120b0a0375696318022001" .
            "280912140a0c736974655f757365725f696418032001280912110a097573" .
            "65725f6e616d65180420012809121f0a0673746174757318052001280e32" .
            "0f2e636f72652e55696353746174757312130a0b6372656174655f74696d" .
            "6518062001280312100a087573655f74696d651807200128032a330a0955" .
            "6963537461747573120a0a06554e55534544100012080a04555345441001" .
            "12100a0c494e56414c49444154494f4e100242310a15636f6d2e616b6178" .
            "696e2e70726f746f2e636f7265420855696350726f746fca020d5a616c79" .
            "5c5365727669636573620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

